[project]
name = "simple-ftp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "loguru>=0.7.3",
    "pyftpdlib>=2.0.1",
]
